[filetype]

# Darker OneDark-inspired color scheme for Yazi
# Using a darker color palette:
# Background: #1e2127 (darker than standard OneDark)
# Foreground: #abb2bf
# Black: #1e2127
# Red: #e06c75
# Green: #98c379
# Yellow: #e5c07b
# Blue: #61afef
# Magenta: #c678dd
# Cyan: #56b6c2
# White: #abb2bf
# Gray: #4b5263 (darker than standard OneDark comment color)

rules = [
    # File type indicators
    { name = "*", is = "block", fg = "#528bff" },           # Block device (brighter blue)
    { name = "*", is = "char", fg = "#98c379", bold = true }, # Character device (green)
    { name = "*/", fg = "#56b6c2" },                        # Directory (cyan)
    { name = "*", is = "exec", fg = "#d19a66", bold = true }, # Executable (darker orange)
    { name = "*", is = "fifo", fg = "#c678dd" },            # FIFO (magenta)
    { name = "*", is = "orphan", fg = "#1e2127", bg = "#e06c75", bold = true }, # Broken symlink (red bg)
    { name = "*", is = "sock", fg = "#e06c75" },            # Socket (red)
    { name = "*", is = "sticky", fg = "#56b6c2", bg = "#1e2127" }, # Sticky directory (cyan on darker bg)
    
    # Documentation/README files
    { name = "*.txt", fg = "#abb2bf" },                     # Plain text (default fg)
    { name = "*README*", fg = "#e5c07b", bold = true },     # README files (yellow)
    { name = "*LICENSE*", fg = "#e5c07b", bold = true },    # License files (yellow)
    { name = "*COPYING", fg = "#e5c07b", bold = true },
    { name = "*INSTALL", fg = "#e5c07b", bold = true },
    { name = "*AUTHORS", fg = "#e5c07b", bold = true },
    { name = "*HISTORY", fg = "#e5c07b", bold = true },
    { name = "*CONTRIBUTORS", fg = "#e5c07b", bold = true },
    { name = "*CONTRIBUTING*", fg = "#e5c07b", bold = true },
    { name = "*CHANGELOG*", fg = "#e5c07b", bold = true },
    { name = "*VERSION", fg = "#e5c07b", bold = true },
    { name = "*NOTICE", fg = "#e5c07b", bold = true },
    { name = "*CHANGES", fg = "#e5c07b", bold = true },
    
    # Logs & Documentation formats
    { name = "*.log", fg = "#d19a66" },                     # Log files (darker orange)
    { name = "*.md", fg = "#c678dd" },                      # Markdown (magenta)
    { name = "*.markdown", fg = "#c678dd" },
    { name = "*.rst", fg = "#c678dd" },
    { name = "*.org", fg = "#c678dd" },
    { name = "*.adoc", fg = "#c678dd" },
    { name = "*.asciidoc", fg = "#c678dd" },
    { name = "*.tex", fg = "#c678dd" },
    
    # Data formats
    { name = "*.json", fg = "#d19a66" },                    # JSON (darker orange)
    { name = "*.toml", fg = "#d19a66" },                    # TOML (darker orange)
    { name = "*.yaml", fg = "#d19a66" },                    # YAML (darker orange)
    { name = "*.yml", fg = "#d19a66" },                     # YAML (darker orange)
    { name = "*.xml", fg = "#d19a66" },                     # XML (darker orange)
    { name = "*.csv", fg = "#56b6c2" },                     # CSV (cyan)
    
    # Programming languages
    { name = "*.sh", fg = "#98c379" },                      # Shell (green)
    { name = "*.bash", fg = "#98c379" },                    # Bash (green)
    { name = "*.zsh", fg = "#98c379" },                     # Zsh (green)
    { name = "*.py", fg = "#56b6c2" },                      # Python (cyan)
    { name = "*.js", fg = "#d19a66", bold = true },         # JavaScript (darker orange)
    { name = "*.ts", fg = "#528bff", bold = true },         # TypeScript (brighter blue)
    { name = "*.jsx", fg = "#d19a66", bold = true },        # JSX (darker orange)
    { name = "*.tsx", fg = "#528bff", bold = true },        # TSX (brighter blue)
    { name = "*.c", fg = "#56b6c2" },                       # C (cyan)
    { name = "*.cpp", fg = "#56b6c2" },                     # C++ (cyan)
    { name = "*.h", fg = "#528bff" },                       # Header (brighter blue)
    { name = "*.rs", fg = "#e06c75" },                      # Rust (red)
    { name = "*.go", fg = "#56b6c2" },                      # Go (cyan)
    { name = "*.rb", fg = "#e06c75" },                      # Ruby (red)
    { name = "*.php", fg = "#c678dd" },                     # PHP (magenta)
    { name = "*.java", fg = "#e06c75", bold = true },       # Java (red)
    { name = "*.lua", fg = "#528bff" },                     # Lua (brighter blue)
    { name = "*.hs", fg = "#c678dd" },                      # Haskell (magenta)
    { name = "*.css", fg = "#56b6c2", bold = true },        # CSS (cyan)
    { name = "*.scss", fg = "#c678dd", bold = true },       # SCSS (magenta)
    { name = "*.html", fg = "#e06c75", bold = true },       # HTML (red)
    { name = "*.vue", fg = "#98c379", bold = true },        # Vue (green)
    { name = "*.svelte", fg = "#e06c75", bold = true },     # Svelte (red)
    { name = "*.nix", fg = "#528bff" },                     # Nix (brighter blue)
    
    # Config files
    { name = "*config", bold = true },                      # Generic config
    { name = "*rc", bold = true },                          # RC files
    { name = "*conf", bold = true },                        # Conf files
    { name = "*.ini", bold = true },                        # INI files
    { name = "*.yaml", bold = true },                       # YAML config
    { name = "*.yml", bold = true },                        # YML config
    
    # Git related
    { name = "*.git", fg = "#e06c75" },                     # Git dir (red)
    { name = "*.gitignore", fg = "#4b5263" },               # Gitignore (darker gray)
    { name = "*.gitmodules", fg = "#4b5263" },              # Gitmodules (darker gray)
    
    # Media files
    { name = "*.png", fg = "#c678dd" },                     # PNG (magenta)
    { name = "*.jpg", fg = "#c678dd" },                     # JPG (magenta)
    { name = "*.jpeg", fg = "#c678dd" },                    # JPEG (magenta)
    { name = "*.gif", fg = "#c678dd" },                     # GIF (magenta)
    { name = "*.webp", fg = "#c678dd" },                    # WEBP (magenta)
    { name = "*.svg", fg = "#c678dd" },                     # SVG (magenta)
    { name = "*.mp3", fg = "#98c379", bold = true },        # MP3 (green)
    { name = "*.flac", fg = "#98c379", bold = true },       # FLAC (green)
    { name = "*.wav", fg = "#98c379", bold = true },        # WAV (green)
    { name = "*.mp4", fg = "#98c379" },                     # MP4 (green)
    { name = "*.mkv", fg = "#98c379" },                     # MKV (green)
    { name = "*.webm", fg = "#98c379" },                    # WEBM (green)
    
    # Archives
    { name = "*.zip", fg = "#528bff" },                     # ZIP (brighter blue)
    { name = "*.tar", fg = "#528bff" },                     # TAR (brighter blue)
    { name = "*.gz", fg = "#528bff" },                      # GZ (brighter blue)
    { name = "*.xz", fg = "#528bff" },                      # XZ (brighter blue)
    { name = "*.bz2", fg = "#528bff" },                     # BZ2 (brighter blue)
    { name = "*.7z", fg = "#528bff" },                      # 7Z (brighter blue)
    { name = "*.rar", fg = "#528bff" },                     # RAR (brighter blue)
    
    # Documents
    { name = "*.pdf", fg = "#c678dd" },                     # PDF (magenta)
    { name = "*.docx", fg = "#528bff" },                    # DOCX (brighter blue)
    { name = "*.xlsx", fg = "#98c379" },                    # XLSX (green)
    { name = "*.pptx", fg = "#e5c07b" },                    # PPTX (yellow)
    
    # Temporary/System files
    { name = "*.swp", fg = "#3e4452" },                     # Swap files (very dark gray)
    { name = "*.tmp", fg = "#3e4452" },                     # Temp files (very dark gray)
    { name = "*.bak", fg = "#3e4452" },                     # Backup files (very dark gray)
    { name = "*.~*", fg = "#3e4452" },                      # Backup files (very dark gray)
    { name = "*.o", fg = "#3e4452" },                       # Object files (very dark gray)
    { name = "*.class", fg = "#3e4452" },                   # Java class files (very dark gray)
    { name = "*.pyc", fg = "#3e4452" },                     # Python cache (very dark gray)
    { name = ".DS_Store", fg = "#3e4452" },                 # macOS (very dark gray)

    # Hidden files (darker gray for less visibility)
    { name = ".*", fg = "#3e4452" },                        # All hidden files (very dark gray)
    
    # Binary files
    { name = "*.exe", fg = "#d19a66", bold = true },        # Windows executables (darker orange)
    { name = "*.dll", fg = "#3e4452" },                     # DLLs (very dark gray)
    { name = "*.so", fg = "#3e4452" },                      # Shared objects (very dark gray)
    { name = "*.dylib", fg = "#3e4452" },                   # Dynamic libraries (very dark gray)
    
    # Databases
    { name = "*.db", fg = "#c678dd" },                      # Database files (magenta)
    { name = "*.sqlite", fg = "#c678dd" },                  # SQLite databases (magenta)
    
    # Error files
    { name = "*.err", fg = "#e06c75", bold = true },        # Error files (bold red)
    { name = "*.error", fg = "#e06c75", bold = true },      # Error files (bold red)
]
